[tooling]


[todo]
172.31.24.27 ansible_ssh_user='ec2-user'

#[nginx]
#172.31.20.135 ansible_ssh_user='ubuntu'

#[db:vars]
#ansible_user=ec2-user
#ansible_python_interpreter=/usr/bin/python

[db]
#172.31.30.95 ansible_ssh_user='ubuntu'