---
- hosts: all

#- name: Include dynamic variables
 # import_playbook: ../static-assignment/common.yml
 # include: ../dynamic-assignments/env-vars.yml
 # tags:
  #  - always

#- name: Delete wireshark installation
 # import_playbook: ../static-assignment/common-del.yml

#- name: webserver
#  import_playbook: ../static-assignment/webservers.yml

#- name: Loadbalancers assignment
#  import_playbook: ../static-assignment/loadbalancers.yml
#  when: load_balancer_is_required

#- name: install artifactory
 # import_playbook: ../static-assignment/artifactory.yml
- name: install mysql database
  import_playbook: ../static-assignment/database.yml